# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 53f30dfea89b07ef16185427b428a4bb54449992f57c701ced4e7654daa2c29a05d0d698d2f81565d72e26737c911a55caf73db34de1e2494b02800f88191582

test:
  secret_key_base: 88cd82063e30dde6caaa5e59eb9ab57dbfed99d0ba526e019648faf69912c81a35d51b0a37021badaf9ddbb42af978df28752234ac2947beacdf3170455be363

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
